// Code generated by MockGen. DO NOT EDIT.
// Source: internal/user/delivery/http/handler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/dunooo0ooo/avito-test-task/internal/pullrequest/domain"
	domain0 "github.com/dunooo0ooo/avito-test-task/internal/user/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// DeactivateTeamUsersAndReassign mocks base method.
func (m *MockUserService) DeactivateTeamUsersAndReassign(ctx context.Context, teamName string, userIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateTeamUsersAndReassign", ctx, teamName, userIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateTeamUsersAndReassign indicates an expected call of DeactivateTeamUsersAndReassign.
func (mr *MockUserServiceMockRecorder) DeactivateTeamUsersAndReassign(ctx, teamName, userIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateTeamUsersAndReassign", reflect.TypeOf((*MockUserService)(nil).DeactivateTeamUsersAndReassign), ctx, teamName, userIDs)
}

// GetUserReviews mocks base method.
func (m *MockUserService) GetUserReviews(ctx context.Context, userID string) (*domain.UserReviews, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserReviews", ctx, userID)
	ret0, _ := ret[0].(*domain.UserReviews)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserReviews indicates an expected call of GetUserReviews.
func (mr *MockUserServiceMockRecorder) GetUserReviews(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserReviews", reflect.TypeOf((*MockUserService)(nil).GetUserReviews), ctx, userID)
}

// SetIsActive mocks base method.
func (m *MockUserService) SetIsActive(ctx context.Context, userID string, active bool) (*domain0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetIsActive", ctx, userID, active)
	ret0, _ := ret[0].(*domain0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetIsActive indicates an expected call of SetIsActive.
func (mr *MockUserServiceMockRecorder) SetIsActive(ctx, userID, active interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIsActive", reflect.TypeOf((*MockUserService)(nil).SetIsActive), ctx, userID, active)
}
