// Code generated by MockGen. DO NOT EDIT.
// Source: internal/user/domain/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/dunooo0ooo/avito-test-task/internal/user/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// AddTeamMembers mocks base method.
func (m *MockUserRepository) AddTeamMembers(ctx context.Context, teamName string, members []domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTeamMembers", ctx, teamName, members)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTeamMembers indicates an expected call of AddTeamMembers.
func (mr *MockUserRepositoryMockRecorder) AddTeamMembers(ctx, teamName, members interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTeamMembers", reflect.TypeOf((*MockUserRepository)(nil).AddTeamMembers), ctx, teamName, members)
}

// DeactivateByTeam mocks base method.
func (m *MockUserRepository) DeactivateByTeam(ctx context.Context, teamName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateByTeam", ctx, teamName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateByTeam indicates an expected call of DeactivateByTeam.
func (mr *MockUserRepositoryMockRecorder) DeactivateByTeam(ctx, teamName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateByTeam", reflect.TypeOf((*MockUserRepository)(nil).DeactivateByTeam), ctx, teamName)
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(ctx context.Context, id string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), ctx, id)
}

// ListByTeam mocks base method.
func (m *MockUserRepository) ListByTeam(ctx context.Context, teamName string) ([]*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTeam", ctx, teamName)
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTeam indicates an expected call of ListByTeam.
func (mr *MockUserRepositoryMockRecorder) ListByTeam(ctx, teamName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTeam", reflect.TypeOf((*MockUserRepository)(nil).ListByTeam), ctx, teamName)
}

// UpdateActive mocks base method.
func (m *MockUserRepository) UpdateActive(ctx context.Context, id string, active bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateActive", ctx, id, active)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateActive indicates an expected call of UpdateActive.
func (mr *MockUserRepositoryMockRecorder) UpdateActive(ctx, id, active interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateActive", reflect.TypeOf((*MockUserRepository)(nil).UpdateActive), ctx, id, active)
}
