// Code generated by MockGen. DO NOT EDIT.
// Source: internal/stats/delivery/http/handler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/dunooo0ooo/avito-test-task/internal/stats/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockStatsService is a mock of StatsService interface.
type MockStatsService struct {
	ctrl     *gomock.Controller
	recorder *MockStatsServiceMockRecorder
}

// MockStatsServiceMockRecorder is the mock recorder for MockStatsService.
type MockStatsServiceMockRecorder struct {
	mock *MockStatsService
}

// NewMockStatsService creates a new mock instance.
func NewMockStatsService(ctrl *gomock.Controller) *MockStatsService {
	mock := &MockStatsService{ctrl: ctrl}
	mock.recorder = &MockStatsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsService) EXPECT() *MockStatsServiceMockRecorder {
	return m.recorder
}

// GetReviewerStats mocks base method.
func (m *MockStatsService) GetReviewerStats(ctx context.Context) ([]domain.ReviewerStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviewerStats", ctx)
	ret0, _ := ret[0].([]domain.ReviewerStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReviewerStats indicates an expected call of GetReviewerStats.
func (mr *MockStatsServiceMockRecorder) GetReviewerStats(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviewerStats", reflect.TypeOf((*MockStatsService)(nil).GetReviewerStats), ctx)
}
