// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pullrequest/delivery/http/handler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/dunooo0ooo/avito-test-task/internal/pullrequest/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockPullRequestService is a mock of PullRequestService interface.
type MockPullRequestService struct {
	ctrl     *gomock.Controller
	recorder *MockPullRequestServiceMockRecorder
}

// MockPullRequestServiceMockRecorder is the mock recorder for MockPullRequestService.
type MockPullRequestServiceMockRecorder struct {
	mock *MockPullRequestService
}

// NewMockPullRequestService creates a new mock instance.
func NewMockPullRequestService(ctrl *gomock.Controller) *MockPullRequestService {
	mock := &MockPullRequestService{ctrl: ctrl}
	mock.recorder = &MockPullRequestServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPullRequestService) EXPECT() *MockPullRequestServiceMockRecorder {
	return m.recorder
}

// CreatePullRequest mocks base method.
func (m *MockPullRequestService) CreatePullRequest(ctx context.Context, id, name, authorID string) (*domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePullRequest", ctx, id, name, authorID)
	ret0, _ := ret[0].(*domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePullRequest indicates an expected call of CreatePullRequest.
func (mr *MockPullRequestServiceMockRecorder) CreatePullRequest(ctx, id, name, authorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePullRequest", reflect.TypeOf((*MockPullRequestService)(nil).CreatePullRequest), ctx, id, name, authorID)
}

// MergePullRequest mocks base method.
func (m *MockPullRequestService) MergePullRequest(ctx context.Context, id string) (*domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergePullRequest", ctx, id)
	ret0, _ := ret[0].(*domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MergePullRequest indicates an expected call of MergePullRequest.
func (mr *MockPullRequestServiceMockRecorder) MergePullRequest(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergePullRequest", reflect.TypeOf((*MockPullRequestService)(nil).MergePullRequest), ctx, id)
}

// ReassignReviewer mocks base method.
func (m *MockPullRequestService) ReassignReviewer(ctx context.Context, prID, oldReviewerID string) (*domain.PullRequest, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReassignReviewer", ctx, prID, oldReviewerID)
	ret0, _ := ret[0].(*domain.PullRequest)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReassignReviewer indicates an expected call of ReassignReviewer.
func (mr *MockPullRequestServiceMockRecorder) ReassignReviewer(ctx, prID, oldReviewerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReassignReviewer", reflect.TypeOf((*MockPullRequestService)(nil).ReassignReviewer), ctx, prID, oldReviewerID)
}
