// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pullrequest/domain/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/dunooo0ooo/avito-test-task/internal/pullrequest/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockPullRequestRepository is a mock of PullRequestRepository interface.
type MockPullRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPullRequestRepositoryMockRecorder
}

// MockPullRequestRepositoryMockRecorder is the mock recorder for MockPullRequestRepository.
type MockPullRequestRepositoryMockRecorder struct {
	mock *MockPullRequestRepository
}

// NewMockPullRequestRepository creates a new mock instance.
func NewMockPullRequestRepository(ctrl *gomock.Controller) *MockPullRequestRepository {
	mock := &MockPullRequestRepository{ctrl: ctrl}
	mock.recorder = &MockPullRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPullRequestRepository) EXPECT() *MockPullRequestRepositoryMockRecorder {
	return m.recorder
}

// CountByReviewer mocks base method.
func (m *MockPullRequestRepository) CountByReviewer(ctx context.Context) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByReviewer", ctx)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByReviewer indicates an expected call of CountByReviewer.
func (mr *MockPullRequestRepositoryMockRecorder) CountByReviewer(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByReviewer", reflect.TypeOf((*MockPullRequestRepository)(nil).CountByReviewer), ctx)
}

// Create mocks base method.
func (m *MockPullRequestRepository) Create(ctx context.Context, pr *domain.PullRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, pr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPullRequestRepositoryMockRecorder) Create(ctx, pr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPullRequestRepository)(nil).Create), ctx, pr)
}

// GetByID mocks base method.
func (m *MockPullRequestRepository) GetByID(ctx context.Context, id string) (*domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPullRequestRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPullRequestRepository)(nil).GetByID), ctx, id)
}

// ListByReviewer mocks base method.
func (m *MockPullRequestRepository) ListByReviewer(ctx context.Context, reviewerID string) ([]domain.PullRequestShort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByReviewer", ctx, reviewerID)
	ret0, _ := ret[0].([]domain.PullRequestShort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByReviewer indicates an expected call of ListByReviewer.
func (mr *MockPullRequestRepositoryMockRecorder) ListByReviewer(ctx, reviewerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByReviewer", reflect.TypeOf((*MockPullRequestRepository)(nil).ListByReviewer), ctx, reviewerID)
}

// ListOpenByReviewers mocks base method.
func (m *MockPullRequestRepository) ListOpenByReviewers(ctx context.Context, reviewerIDs []string) ([]domain.PullRequestShort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOpenByReviewers", ctx, reviewerIDs)
	ret0, _ := ret[0].([]domain.PullRequestShort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOpenByReviewers indicates an expected call of ListOpenByReviewers.
func (mr *MockPullRequestRepositoryMockRecorder) ListOpenByReviewers(ctx, reviewerIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOpenByReviewers", reflect.TypeOf((*MockPullRequestRepository)(nil).ListOpenByReviewers), ctx, reviewerIDs)
}

// SetReviewers mocks base method.
func (m *MockPullRequestRepository) SetReviewers(ctx context.Context, id string, reviewerIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetReviewers", ctx, id, reviewerIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetReviewers indicates an expected call of SetReviewers.
func (mr *MockPullRequestRepositoryMockRecorder) SetReviewers(ctx, id, reviewerIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReviewers", reflect.TypeOf((*MockPullRequestRepository)(nil).SetReviewers), ctx, id, reviewerIDs)
}

// UpdateStatus mocks base method.
func (m *MockPullRequestRepository) UpdateStatus(ctx context.Context, id string, status domain.PRStatus, mergedAt *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status, mergedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockPullRequestRepositoryMockRecorder) UpdateStatus(ctx, id, status, mergedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockPullRequestRepository)(nil).UpdateStatus), ctx, id, status, mergedAt)
}
